- name: Configure Kubernetes Master as Jenkins Agent
  hosts: kubernetes_master
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
