- name: Initialize Kubernetes Master
  hosts: kubernetes_master
  become: true

  tasks:
    - name: Initialize Kubernetes control plane
      command: >
        kubeadm init
        --apiserver-advertise-address=10.0.1.185
        --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kubeconfig directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy Kubernetes admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: "0600"
